language: java
jdk:
- oraclejdk8
sudo: required
services:
- docker
- memcached
os:
- linux
env:
  global:
  - RDS_ADDRESS=127.0.0.1
install:
script: ./deploy.sh
cache:
  bundler: true
  apt: true
  directories:
  - $HOME/.m2
  - $HOME/.cache/pip
before_script:
- chmod +x ./deploy.sh
